### ISSUE TITLE
Add read excel functionality using the `external_location`

### ISSUE THREAD

**Issue by JCZuurmond** [godatadriven/dbt-excel#2]

**Comment by hgrif** [comment]
Multiple approaches:

# 1 Source with a `external_location`  

## Usage 

Add a source in a `schema.yml`:

```
sources:
  - name: "my_external"
    meta:
      external_location: "/Users/henkgriffioen/gdd/dbt-excel/dbt_project/{name}.xlsx"
    tables:
      - name: output1
```

Use it in a model:

```
select *
from {{ source('my_external', 'output1') }}
where id = 1
```

## 1.1 Approach: `DuckDBRelation.create_from_source`

Check if external location ends with .xlsx, if so:
- Read Excel, convert to CSV
- Replace external location with path to CSV

Disadvantages:
- Not sure how to manage the intermediate CSVs

## 1.2 Approach: `DuckDBConnectionManager.execute`

Catch all queries done on Excels and replace them by queries on intermediate CSV.

Disadvantages
- Low level
- Queries parsing is brittle

## 1.3 Approach: `source()`

Overwrite the `source()` macro to deal with Excel files.
